# Generated by Django 2.0.3 on 2018-03-23 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(verbose_name='メモ')),
                ('start_time', models.TimeField(default=datetime.time(0, 0), verbose_name='開始時間')),
                ('end_time', models.TimeField(default=datetime.time(0, 0), verbose_name='終了時間')),
            ],
        ),
    ]
